# -*- coding: utf-8 -*-
"""Code for DRP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m4kZ5dZA3Q7lGIMvyDgg78w-K9FsQIE-
"""

#Here is a code that demonstrates how accurately we can approximate
#the solution to a linear dynamical system at a specific time,
#using eulers method, which is known to have a linear big O.

import numpy as np #so that we can build a matrix
from scipy.linalg import expm #this is to get the exponential function which we need

A = np.array ([[0, 1],
               [-1, 0]]) #This is just an example of a matrix, this can be changed

x0 = np.array ([1,0]) #This is our intial condition
tfinal = 2.0 #this is how long we want to run our Eulers Method

#dt list
dt_list = np.arange(1, 0, -0.1)

#Analytical Solution
xprecise = expm(A*tfinal)@x0 # the @ symbol is for matrix multiplication.

#Add the error array to store the errors:
errors = []

#implementing Eulers method and testing for different dt values
for dt in dt_list: #Here are all the dt values we want to test for
    n = int(tfinal/dt) #the number of steps is the total amount of time over the dt which is the different spacings
    #the int above just makes sure that the 'for loop' works and we have the number of steps as an int
    x = x0.copy() #we want to copy the intial condition so you can take the same x0 each time, we dont want to change x0
    I = np.eye(2) #the function to create an identity matrix
    for i in range(n):
        x = (I + A*dt)@x #formula we want to find
    print(f"dt: {dt}")
    print(f"Analytical solution: {xprecise}")
    print(f"Numerical solution: {x}")
    print(f"Error: {np.linalg.norm(x-xprecise)}")
    print()
    errors.append(np.linalg.norm(x-xprecise))
     #we want to find a single number showing the error of the two vectors
    #error=(x1num​−x1exact​)&2+(x2num​−x2exact​)^2, this is the formula for np.linalg.norm

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

# Plot error vs dt (log-log to see convergence rate nicely)
plt.figure()
plt.plot(dt_list, errors, marker='o')
plt.xlabel("dt")
plt.ylabel(f"Error at t = {tfinal}")
plt.title("Euler Method Error vs Step Size")
plt.show()